source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "Sandbox" do
	pod 'Hydra', :path => '~/Workspace/OpenSources/Hydra'
	pod 'HJAsyncHttpDeliverer', :path => '~/Workspace/OpenSources/HJAsyncHttpDeliverer'
end
